Repository radical-cybertools/radical.entk, pull requests merged in 2019-05, with the labels that each got.

#341 remove hardcoded logger targets
  src/radical/entk/appman/appmanager.py
  src/radical/entk/appman/wfprocessor.py
  src/radical/entk/execman/base/resource_manager.py
  src/radical/entk/execman/base/task_manager.py
Labels: layer:rct, priority:low, type:enhancement

#326 GPU CUDA thread type
  src/radical/entk/task/task.py
Labels: layer:rp, priority:critical, topic:execution, topic:resource, type:enhancement

#343 feature: suspend / resume
  examples/misc/async_repex.py
  src/radical/entk/appman/appmanager.py
  src/radical/entk/appman/wfprocessor.py
  src/radical/entk/pipeline/pipeline.py
  src/radical/entk/stage/stage.py
  tests/test_component/test_pipeline.py
  tests/test_component/test_stage.py
Labels: priority:critical, topic:api, topic:execution, type:feature

#347 Fix/documentation
  src/radical/entk/pipeline/pipeline.py
Labels: priority:high, topic:execution, type:documentation
