Repository radical-cybertools/radical.entk, pull requests merged in 2019-12, with the labels that each got.

#379 Accept username/password credentials for RabbitMQ
  src/radical/entk/appman/appmanager.py
  src/radical/entk/appman/config.json
  src/radical/entk/appman/wfprocessor.py
  src/radical/entk/execman/base/task_manager.py
  src/radical/entk/execman/mock/task_manager.py
  src/radical/entk/execman/rp/task_manager.py
Labels: priority:medium, topic:api, topic:communication, type:enhancement

#400 implement fix discussed in #399
  src/radical/entk/appman/wfprocessor.py
Labels: priority:critical, topic:communication, topic:execution, type:bug

#396 add unit tests for RMQ auth
  tests/test_component/test_amgr.py
Labels: priority:medium, topic:testing, type:enhancement
