Repository radical-cybertools/radical.entk, pull requests merged in 2019-02, with the labels that each got.

#297 allow any callble for post_exec hooks
  docs/introduction.rst
  src/radical/entk/stage/stage.py
  tests/test_component/test_stage.py
Labels: Replica Exchange, priority:high, topic:communication, type:enhancement

#305 Fix/issue 303
  docs/adv_examples/adapt_ta.rst
  docs/adv_examples/adapt_tc.rst
  docs/adv_examples/adapt_to.rst
  docs/entk.rst
  docs/examples/eop.rst
  docs/examples/poe.rst
  docs/install.rst
  docs/introduction.rst
  docs/user_guide/adding_data.rst
  docs/user_guide/adding_pipelines.rst
  docs/user_guide/adding_shared_data.rst
  docs/user_guide/change_target.rst
  docs/user_guide/get_started.rst
Labels: type:documentation

#307 implement long uids
  src/radical/entk/appman/appmanager.py
  src/radical/entk/pipeline/pipeline.py
  src/radical/entk/stage/stage.py
  src/radical/entk/task/task.py
Labels: priority:medium, topic:api, type:enhancement
