Repository radical-cybertools/radical.entk, pull requests merged in 2022-02, with the labels that each got.

#600 Entk resource descr. memory
  src/radical/entk/execman/base/resource_manager.py
  src/radical/entk/execman/rp/resource_manager.py
  tests/test_component/test_amgr.py
  tests/test_component/test_pipeline.py
  tests/test_component/test_rmgr_base.py
  tests/test_component/test_rmgr_rp.py
  tests/test_component/test_stage.py
Labels: layer:entk, priority:high, topic:resource, type:bug

#570 Update Task to Munch
  setup.py
  src/radical/entk/appman/appmanager.py
  src/radical/entk/appman/wfprocessor.py
  src/radical/entk/constants.py
  src/radical/entk/exceptions.py
  src/radical/entk/execman/mock/task_manager.py
  src/radical/entk/execman/rp/task_manager.py
  src/radical/entk/execman/rp/task_processor.py
  src/radical/entk/stage.py
  src/radical/entk/task.py
  tests/test_component/test_amgr.py
  tests/test_component/test_stage.py
  tests/test_component/test_task.py
  tests/test_component/test_tmgr_base.py
  tests/test_component/test_tproc_rp.py
  tests/test_integration/test_tmgr_rp/test_tproc_rp.py
Labels: priority:medium, topic:api, type:enhancement

#602 CI: use RCT devel packages
  .coveragerc
  .github/workflows/python-app.yml
Labels: priority:medium, topic:testing

#603 Changes after `TypedDict` got introduced
  src/radical/entk/appman/wfprocessor.py
  src/radical/entk/execman/base/task_manager.py
  src/radical/entk/execman/mock/task_manager.py
  src/radical/entk/execman/rp/task_manager.py
  src/radical/entk/pipeline.py
  src/radical/entk/stage.py
  src/radical/entk/task.py
  src/radical/entk/utils/prof_utils.py
  tests/test_component/test_pipeline.py
  tests/test_component/test_stage.py
  tests/test_component/test_task.py
  tests/test_component/test_tmgr_base.py
  tests/test_integration/test_tmgr_base/test_heartbeat.py
  tests/test_integration/test_tmgr_base/test_rmq_integration.py
  tests/test_integration/test_tmgr_base/test_sync_with_master.py
  tests/test_utils/test_prof_utils.py
Labels: layer:utils, priority:medium

#605 Hotfix/no res check
  src/radical/entk/execman/rp/task_manager.py
Labels: priority:high, topic:resource, type:enhancement

#606 fix dep versions
  setup.py
Labels: priority:medium
