Repository radical-cybertools/radical.entk, pull requests merged in 2023-01, with the labels that each got.

#628 Sync with RP Task attributes `tags` - `exclusive`
  src/radical/entk/execman/rp/task_processor.py
  src/radical/entk/task.py
  tests/test_component/test_task.py
  tests/test_component/test_tproc_rp.py
  tests/test_integration/test_tmgr_rp/test_tproc_rp.py
Labels: priority:medium, topic:api, type:feature

#633 Docs/no rmq
  docs/source/dev_docs/tests.rst
  docs/source/entk.rst
  docs/source/examples.rst
  docs/source/install.rst
  docs/source/introduction.rst
  docs/source/user_guide/adding_shared_data.rst
  docs/source/user_guide/adding_tasks.rst
  docs/source/user_guide/change_target.rst
  docs/source/user_guide/get_started.rst
Labels: priority:medium, type:bug, type:documentation

#630 Fix/mock
  .github/workflows/python-app.yml
  .github/workflows/python-publish.yml
  .pylintrc
  docs/source/dev_docs/tests.rst
  docs/source/entk.rst
  docs/source/examples.rst
  docs/source/install.rst
  docs/source/introduction.rst
  docs/source/user_guide/adding_shared_data.rst
  docs/source/user_guide/adding_tasks.rst
  docs/source/user_guide/change_target.rst
  docs/source/user_guide/get_started.rst
  examples/misc/lfs_tagging_dd.py
  examples/misc/scale.py
  examples/misc/scale.sh
  examples/misc/suspend_pipelines.py
  examples/simple/eop.py
  examples/simple/poe.py
  examples/simple/sow.py
  examples/user_guide/add_data.py
  examples/user_guide/add_pipelines.py
  examples/user_guide/add_shared_data.py
  examples/user_guide/add_stages.py
  examples/user_guide/add_tasks.py
  examples/user_guide/change_target.py
  examples/user_guide/get_started.py
  requirements-tests.txt
  requirements.txt
  src/radical/entk/__init__.py
  src/radical/entk/appman/__init__.py
  src/radical/entk/appman/appmanager.py
  src/radical/entk/appman/config.json
  src/radical/entk/appman/wfprocessor.py
  src/radical/entk/exceptions.py
  src/radical/entk/execman/base/__init__.py
  src/radical/entk/execman/base/resource_manager.py
  src/radical/entk/execman/base/task_manager.py
  src/radical/entk/execman/mock/__init__.py
  src/radical/entk/execman/mock/resource_manager.py
  src/radical/entk/execman/mock/task_manager.py
  src/radical/entk/execman/rp/resource_manager.py
  src/radical/entk/execman/rp/task_manager.py
  src/radical/entk/execman/rp/task_processor.py
  src/radical/entk/pipeline.py
  src/radical/entk/stage.py
  src/radical/entk/task.py
  tests/test_component/test_amgr.py
  tests/test_component/test_pipeline.py
  tests/test_component/test_rmgr_base.py
  tests/test_component/test_rmgr_rp.py
  tests/test_component/test_stage.py
  tests/test_component/test_task.py
  tests/test_component/test_tmgr_base.py
  tests/test_component/test_tmgr_rp.py
  tests/test_component/test_tproc_rp.py
  tests/test_component/test_wfp.py
  tests/test_integration/test_amgr/test_amgr.py
  tests/test_integration/test_tmgr_base/test_heartbeat.py
  tests/test_integration/test_tmgr_base/test_rmq_integration.py
  tests/test_integration/test_tmgr_base/test_sync_with_master.py
Labels: priority:medium, topic:execution, type:bug

#634 response to comments
  docs/source/misc/Dockerfile
  examples/misc/scale.py
  src/radical/entk/appman/appmanager.py
  src/radical/entk/appman/config.json
  tests/test_component/test_amgr.py
  tests/test_component/test_tmgr_rp.py
  tests/test_component/test_wfp.py
Labels: priority:medium, topic:api, type:enhancement

#631 Fix/mock no rmq
  .flake8
  examples/misc/scale.py
  requirements-tests.txt
  src/radical/entk/appman/appmanager.py
  src/radical/entk/appman/wfprocessor.py
  src/radical/entk/execman/mock/task_manager.py
  src/radical/entk/execman/rp/task_manager.py
Labels: priority:medium, topic:execution, type:bug
